### ISSUE TITLE
Crear y migrar models de aplicación  

### ISSUE THREAD

**Issue by esgaelramos** [esgaelramos/MyMoneyUP#19]
Discutir estructura y diseño de base de datos para la aplicación inicial
Normalizar y diagramar base de datos

**Comment by LorenzoFerreyra** [comment]
Falta migrar

**Comment by LorenzoFerreyra** [comment]
Nota: Eliminamos campo Sessions e implementamos CustomUser, que hereda de User, campo default de Django.

**Comment by esgaelramos** [comment]
DIAGRAMA ACTUAL 1
por si quieren replicarlo y jugar con la herramienta:
https://app.quickdatabasediagrams.com/#/
"""
# Modify this code to update the DB schema diagram.

User
--
id PK int

CustomUser
----------
id PK int
suscribed boolean
user_id int FK >- User.id

Asset
-----
id PK int
name varchar(255)
symbol varchar(10)
type varchar(50)

Portfolio
---------
id PK int
user_id int FK >- CustomUser.id

PortfolioAsset
--------------
id PK int
portfolio_id int FK >- Portfolio.id
asset_id int FK >- Asset.id
quantity decimal(18,8)
acquisition_date date

Performance
-----------
id PK int
user_id int FK >- CustomUser.id
date date
days_to_send_email int
total_portfolio_value decimal(18,8)
"""

**Comment by esgaelramos** [comment]
DIAGRAMA PROPUESTA 2
por si quieren replicarlo y jugar con la herramienta:
https://app.quickdatabasediagrams.com/#/
```
# Modify this code to update the DB schema diagram.

User
--
id PK int

CustomUser
----------
id PK int
suscribed boolean
user_id int FK >- User.id

Asset
-----
id PK int
name varchar(255)
symbol varchar(10)
type varchar(50)

Portfolio
---------
id PK int
user_id int FK >- CustomUser.id

PortfolioAsset
--------------
id PK int
portfolio_id int FK >- Portfolio.id
asset_id int FK >- Asset.id
quantity decimal(18,8)
acquisition_date date

Performance
-----------
id PK int
user_id int FK >- CustomUser.id
date date
days_to_send_email int
total_portfolio_value decimal(18,8)
```

**Comment by esgaelramos** [comment]
Sí, para esa característica los models actuales no lo soporte, acá lo que se me ocurre a priori:

- Registro de Transacciones/Cambios: crear su entidad con la fecha, la cantidad que cambió, que permita reconstruir el estado del portafolio
- NO RECOMANDADO? 'Snapshots' Períodicos del portafolio así como su valor, para mantener cada x días lo que vale

A mi parecer lo mejor es tener un campo extra para sus transacciones, para que refleje si agrega o quita assets, y ya con eso y la API que mencionas puede ser suficiente para mantener un historial

Sin embargo, eso ya se considera fase 2, y por ahora con lo que se tiene podría operar lo más básico

**Comment by esgaelramos** [comment]
Vava @ogarcia-dev, me gusta y tienes razón, faltó poner algunos dentro de ese model, por ahora van a pasar así, para que en la fase 1, ya se pueda correr, pero cuándo estés libre y le puedas echar mano a los models, siéntete libre: https://github.com/esgaelramos/YourMoneyTrackerMail/pull/54/files

**Comment by CamilaPua** [comment]
Gracias @ogarcia-dev !

- [ ] Poner default en el PortfolioAsset en quantity
