### ISSUE TITLE
check visibility of scripts for populate, delete and backup in server

### ISSUE THREAD

**Issue by esgaelramos** [esgaelramos/MyMoneyUP#77]
- [x] populate in prod
- [x] delete in prod
- [x] backup in prod

**Comment by CamilaPua** [comment]
what do you mean with visibility?

**Comment by esgaelramos** [comment]
I mean, we have two options:
+ Add scripts to the repository (only if the code don't have bad practices of security)
+ Or add the register of his existing into .gitignore for good practice and skip gjt conflicts
