### ISSUE TITLE
delete examples on data_init for assets (db)

### ISSUE THREAD

**Issue by CamilaPua** [esgaelramos/MyMoneyUP#95]
![image](https://github.com/esgaelramos/MyMoneyUP/assets/121822505/ef5eec53-8339-4dee-abce-1f17ef85ed11)

**Comment by esgaelramos** [comment]
because exist the script for assync:)

**Comment by JorgeGarcia-Dev** [comment]
Done: https://github.com/esgaelramos/MyMoneyUP/commit/67cbcd1eb3b77fc27ad6680d4edd9e28f7e735b4
